responder_pergunta_compliance:
  description: >
    Responder perguntas relacionadas à conformidade com base nas regulamentações da ANVISA, BPF e GMP que está nos arquivos PDF.
    Fornecer a seçãi naus relevante das regulamentaç~ies e resumi-la de forma clara.

    Pergunta:
    {pergunta}

  expected_output: >
    Uma resposta precisa e bem estruturada, fundamentada nas regulamentações mais relevantes sobre conformidades.
    Se aplicável, citar a seção específica das BPF, RDC nº 301 ou RDC nº 658.

  agent: especialista_compliance